# parameters for the significance experiments with synthetic datasets
n_inits: 10
n_folds: 5
init_type: "minmax"
tol: 1.e-5
reg_covar: 1.e-12
max_iter: 10000
bootstrap: True
fixed_components: False
n_bootstrap: 100
MC_samples: 1.e+5
select_c: 'valid'
patience: 1
verbose: False
return_lcurves: False