# parameters for the KSG/MINE/GMM-MI comparison, notebooks 5-8
n_inits: 3
n_folds: 2
init_type: "random_sklearn"
threshold_fit: 1.e-5
reg_covar: 1.e-12
max_iter: 10000
bootstrap: True
n_bootstrap: 100
MC_samples: 1.e+4
metric_method: 'valid'
patience: 1
verbose: False
return_lcurves: False