# parameters for the significance experiments with synthetic datasets, notebooks 1-4
n_inits: 10
n_folds: 5
init_type: "random_sklearn"
threshold_fit: 1.e-6
reg_covar: 1.e-12
max_iter: 10000
bootstrap: True
n_bootstrap: 100
MC_samples: 1.e+5
metric_method: 'valid'
patience: 1
verbose: False
return_lcurves: False